# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Atlan Pte. Ltd.
FROM ghcr.io/atlanhq/atlan-java:1.6.0

LABEL org.opencontainers.image.vendor="Atlan Pte. Ltd." \
      org.opencontainers.image.source="https://github.com/atlanhq/atlan-kotlin-samples" \
      org.opencontainers.image.description="Atlan samples image for Kotlin scripts." \
      org.opencontainers.image.licenses=Apache-2

COPY assembly /opt/jars
