# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Atlan Pte. Ltd.
FROM ghcr.io/atlanhq/atlan-java-numaflow@sha256:0b8e363d9e48b2bac2f41ce4dc5588a4e99b06b0a90243fdd853a1bf802cd838

LABEL org.opencontainers.image.vendor="Atlan Pte. Ltd." \
      org.opencontainers.image.source="https://github.com/atlanhq/atlan-kotlin-samples" \
      org.opencontainers.image.description="Atlan samples image for Kotlin scripts." \
      org.opencontainers.image.licenses=Apache-2

COPY assembly /opt/jars
