# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Atlan Pte. Ltd.
FROM ghcr.io/atlanhq/atlan-java-numaflow@sha256:eff245c8e4a5719dea29f1e76d6e3c42cc1277fcf67ce3724d2be990c08d3759

LABEL org.opencontainers.image.vendor="Atlan Pte. Ltd." \
      org.opencontainers.image.source="https://github.com/atlanhq/atlan-kotlin-samples" \
      org.opencontainers.image.description="Atlan samples image for Kotlin scripts." \
      org.opencontainers.image.licenses=Apache-2

COPY assembly /opt/jars
